Leveler update to 3.1 with old style fix and dataconverter removal (#3)
* [leveler] some cleanup

fix not handling levelup on disabled messages

* [minecraftdata] new cmd: [p]minecraft server <IP>

* [minecraftdata] fix exception if no players on server

* [minecraftdata] catch query timeout

* [minecraftdata] cleanup server's motd
add cooldown
add typing indicator on data recieveing

* [minecraftdata] fix exception for another type of motd (description)

* [minecraftdata] change some strings

* [minecraftdata] attempt to add server's icon to embed

* [minecraftdata] fix TypeError

TypeError: argument should be a bytes-like object or ASCII string, not 'list'

* [leveler] fix an exception in rank with text mod enabled

* [minecraftdata][generalchannel] use autohelp

* [leveler] ignore member-related commands if member is bot

* [leveler] fix an exception when user is None

* [leveler] add requirements

* [leveler] move abstract bg to profile backgrounds

* [minecraftdata] upload skins to discord instead of use direct link to craftar

discordapp/discord-api-docs#878

* [minecraftdata] fix exception

* [minecraftdata] [?] no attachments in author url

* [minecraftdata] [?] no spaces in URL?

* [leveler] fix an exception in [p]rep

* [leveler] remove duplicate image

* [leveler] fix predicate is recognizing any message as "yes"

* [adminutils] fix error in [p]purge when days<0

* [adminutils] some "restyle"

* [leveler] use bank currency

* [leveler] fix last change

* [leveler] fix last change once again

* [leveler] use only first character of credits name

* [leveler] move [p]badge and [p]role to [p]lvladmin

* [minecraftdata] fix regex

* [leveler] ignore length of message if it has an attachment(s)

* [minecraftdata] make some changes in MCNickname converter

* [minecraftdata] add discord typing while getting data from crafatar

* [leveler] make (almost) everything an coroutine

* [leveler] fix SyntaxError

* [leveler] move badge from lvladmin to lvlset

* [moreutils] add requirement

* [datautils] fix exception in [p]cperms when channel is not provided

* update README

* [translators] "restyle" [p]ytranslate output

* [datautils] escape names

truncate rolenames

* [datautils] change style of [p]roles

* [minecraftdata] add checks for embed permission

* [minecraftdata] support for any type of MOTD

* [minecraftdata] fix TypeError

* [translators] run YandexTranslate methods in executor

* [translators] fix TypeError

* [steamcommunity] add more data to [p]getserver
execute ServerQuerier in executor

* [steamcommunity] move map under servername in [p]getserver

* [steamcommunity] add more executors to prevent blocking of async

* [minecraftdata] refactor some code

* Revert "[minecraftdata] refactor some code"

This reverts commit d7aff5db

* [minecraftdata] refactor some code

* Black code format

* [adminutils] add cooldown for massnick and resetnicks cmds

add examples of emoji commands usage

* [godvilledata] add some info to installation

* [translators] update requirements

* [weather] show state, if provided
use direct string formatting instead of chat_formatting
(as long as it is escapes other formatting)
place does not requires double quotes if has spaces anymore

* [weather] change some formatting

* [weather] change some formatting, again

* [weather] fix AttributeError

* [weather] some reformatting again

* add "code style | black" badge

*more badges for god of badges*

* [translators] rewrite [p]ytranslate to custom API wrapper

* [weather] fix error in DMs

* update README.md

* update README

* remove [p]convertv2
DataConverter does not exists anymore: Cog-Creators/Red-DiscordBot#2554

* [leveler] unused variables cleanup

* [leveler] replace check for owner with redbot.is_owner

owner-specific commands should work now and for co-owners

* [leveler] fix AttributeError

* [leveler] fix [p]mention not working

* fix codefactor issues

* [adminutils] fix error after from latest commit

* [weather] wrap potential requests in executor

fix possible exception from ebd7337e779d4b8339a5da51def975f85116fda1

* [leveler] optimize imports

* [leveler] reformat code

* [leveler] reformat code

* [leveler] add more async funcs
remove credits formatting from text truncation

* [leveler] remove notation formatting

* [leveler] rewrite [p]lvlset badge available

* [leveler] fix [p]lvlset badge available when all badges removed

* [leveler] change top output to codeblock instead of single lines

partial copy of cb7487adb97904b05e93b011e9c2396ceb86381c

* [leveler] fix TypeError from latest commit

* [leveler] fix NameError from latest commit

* [leveler] remove unnecessary formats

* [leveler] fix [p]top
add logging
do not use bare `except:` (this should fix #4)

* [leveler] fix [p]top again

* [leveler] fix None in `[p]top -rep`

* [leveler] some code refactoring

* [leveler] attempt to use BytesIO instead of writing to disk

* [leveler] attempt to use BytesIO instead of writing to disk [2]

* [datautils] better Union usage

* [datautils] better Union usage

* [datautils] fix AttributeError

* [minecraftdata] fix some black formatting failure

* [leveler] order listbadge and listrole

* [leveler] fix order

* [leveler] black formatting

* [leveler] fix lint issue `expression-not-assigned`

* [minecraftdata] fix server ip parse in [p]mc server

* [datautils] do not show webhooks if no webhooks exists in cinfo

* replace all ✔ with ✅ for better visibility

* black formatting

* [leveler] make more keyword-only arguments

* [leveler] update requirements

* [leveler] remove scipy requirement

* [minecraftdata] try-except for ip resolve in [p]mc server

* [minecraftdata] add return

* [moreutils] use rewrite's channel func to get member for `[p]someone`

* update .gitignore

* [weather] add i18n support

* [translators] add i18n support

* [steamcommunity] add i18n support

* [personalroles] add i18n support

* [moreutils] add i18n support

* [minecraftdata] add i18n support

* [generalchannel] add i18n support

* [datautils] add i18n support

* [adminutils] add i18n support

* [weather] add russian translation

* [translators] fix button name

* [translators] update some texts

* [translators] russian translation

* [translators] fix KeyError

* [translators] fix russian translation for new version

* [translators] fix russian translation for new version

* [translators] fix russian translation for new version

* [translators] fix russian translation for new version

* [translators] fix exception with incorrect base64 string

* [translators] fix exception with incorrect base64 string

* [translators] change string again

* [steamcommunity] fix exception output formatting

* [steamcommunity] add russian translation
update translation template

* [steamcommunity] support for i18n in converters

* [personalroles] fix error when server doesn't have any assigned role

* [personalroles] i18n support + russian translation

* [minecraftdata] i18n support update + russian translation

* [moreutils] russian translation

* [generalchannel] russian translation

* [generalchannel] move formatting

* [datautils] add users field for text channels

* [datautils] update translations + russian trunslation

* [adminutils] add some cooldowns to massnicks

* [adminutils] counter for resetnicks

* [adminutils] russian translation

* [adminutils] add format()

* [adminutils] fix kwarg in resetnicks

* [adminutils] better exception handling in ``[p]emoji add`

fix error when image is incorrect

* [adminutils] russian translation

* [adminutils] russian translation update

* black formatting

* update README.md

* update

* [leveler] add `[p]xpban` cmd
add event `leveler_process_exp(message, exp)`

* [datautils] fix exception when role is empty

* [messageslog] new cog

* [messageslog] add info.json

* [messageslog] add some checks
add channel mention

* [messageslog] add exception handling for embeds sending

* update README.md

* fix i18n filenames

* reformat code

* use dict.get instead of str.replace

* [adminutils]reformat code

* update i18n for latest commits

* [leveler] reset cooldown if bot provided

* [minecraftdata] change cooldown pool for [p]mc server

* [leveler] remove cmd cooldown for [p]rep

* [personalroles] add exception handling for HTTPException
reset cooldown if HTTPException occurred

* [generalchannel] reset cooldown if HTTPException occurred

* [personalroles] update ru-RU localization

* [personalroles] add left users cleanup cmd

* Revert "[personalroles] add left users cleanup cmd"

This reverts commit 976c8e1c

* [personalroles] display deleted roles as id instead of nothing

* [minecraftdata] add i18n support for one string

* [minecraftdata] update ru-RU localization

* [personalroles] add check for role is exist

make check async

* [steamcommunity] refactor some code

* [weather] update json.info

* [adminutils] prevent editing emoji from another server

* [leveler] fix textonly profile when user has no badges

* Support for Red V3.1 (discord.py 1.0.1) (#7)

* [datautils] update for v3.1

* [messageslog] update for v3.1

* [minecraftdata] update for v3.1

* [personalroles] update for v3.1

* [minecraftdata] black style

* [personalroles] change get_user_info to fetch_user

* [leveler] update for V3.1

* [leveler] fix ValueError

ValueError: embedded null byte

* [leveler] seek 0 position of BytesIO

* [minecraftdata] clear formatting in players list
use server's host and port instead of user's input

* [minecraftdata] refactor code

* [steamcommunity] refactor code

* [steamcommunity] check for incorrect steamid32

* [datautils] add banner field to serverinfo
[steamcommunity] update locales

* [messageslog] makes [p]ignore one cmd, instead of group of commands

* [messageslog] black code formatting

some aliases for main command

* [leveler] update info.json

* [minecraftdata] optimise converter
optimise exception handling

* [smmdata] new cog

* [smmdata] rename ru_RU translation file

* [smmdata] update ru-RU translation

* [smmdata] fix exception when no one is cleared the level

* update README.md

* [smmdata] fixes exception when level doesn't have difficulty yet

* [smmdata] fixes another exception when level doesn't have difficulty yet

* [smmdata] return float instead of None

* [smmdata] refactor code

add icon and level's tag to embed

* [smmdata] do not show footer text, if no tag set

* fix cog unloading

* update .gitignore

* [weather] update version key in info.json

* [minecraftdata] refactor code, fix some nickname issues

* supress PyMissingConstructor warning

* [minecraftdata] add `[p]mc cape` command (getting mojang capes)

do some code refactoring

* [smmdata] add an Game Style field

* [smmdata] add [p]maker cmd

refactor code

* [smmdata] more i18n support

* Revert "[smmdata] more i18n support"

This reverts commit 1e7e4ee4

* [smmdata] minor ru-RU translation update

* [translators] kinda refactor [p]googlesay

* [smmdata] add "Uploaded courses" field

* [translators] update translations for [p]googlesay refactor

* [messageslog] fix linting issue

* [leveler] use message_without_command event instead of prefix checking

* [minecraftdata] refactor commands definition

* [reverseimagesearch] new cog

tracemoe is returns 500 for me, needs investigation

* [reverseimagesearch] update info.json

* [reverseimagesearch] implement tracemoe

* [smmdata] fix exception when level was uploaded minutes ago

* [leveler] dispatch `leveler_levelup` event regardless of enabled levelup notifications

* [messageslog] support for ignoring categories

* [leveler] old style with 3.1 support

* [leveler] remove dataconverter

* Fix server images on rank banner and cog unload